"""add tags and mood to gratitude entry

Revision ID: 2159ac311e46
Revises: f2120385af2d
Create Date: 2025-05-13 23:01:45.168415

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2159ac311e46'
down_revision: Union[str, None] = 'f2120385af2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###  
    pass
    # ### end Alembic commands ###
