"""add decision router tables

Revision ID: 3d3de44c7d9a
Revises: 0100a50adac4
Create Date: 2025-09-28 21:51:35.769945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d3de44c7d9a'
down_revision: Union[str, None] = '0100a50adac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('top_action', sa.Enum('expand', 'nudge', 'resurface', name='decision_action'), nullable=False),
    sa.Column('candidates_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signals_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['gratitude_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decision_traces_action', 'decision_traces', ['top_action'], unique=False)
    op.create_index('idx_decision_traces_entry', 'decision_traces', ['entry_id'], unique=False)
    op.create_index('idx_decision_traces_user_created', 'decision_traces', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_decision_traces_id'), 'decision_traces', ['id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('expand', 'nudge', 'resurface', name='decision_action'), nullable=False),
    sa.Column('status', sa.Enum('suggested', 'scheduled', 'executed', 'cancelled', name='action_status'), nullable=False),
    sa.Column('params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['gratitude_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trace_id'], ['decision_traces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_actions_entry', 'actions', ['entry_id'], unique=False)
    op.create_index('idx_actions_type_status', 'actions', ['type', 'status'], unique=False)
    op.create_index('idx_actions_user_created', 'actions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_actions_id'), 'actions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actions_id'), table_name='actions')
    op.drop_index('idx_actions_user_created', table_name='actions')
    op.drop_index('idx_actions_type_status', table_name='actions')
    op.drop_index('idx_actions_entry', table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_decision_traces_id'), table_name='decision_traces')
    op.drop_index('idx_decision_traces_user_created', table_name='decision_traces')
    op.drop_index('idx_decision_traces_entry', table_name='decision_traces')
    op.drop_index('idx_decision_traces_action', table_name='decision_traces')
    op.drop_table('decision_traces')
    # ### end Alembic commands ###
