"""add llm_reminder column

Revision ID: b1f0a48c6b94
Revises: 
Create Date: 2025-05-05 14:24:54.032936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f0a48c6b94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def column_exists(table, column):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    return any(c["name"] == column for c in insp.get_columns(table))

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists("gratitude_entries", "llm_reminder"):
        op.add_column('gratitude_entries', sa.Column('llm_reminder', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if column_exists("gratitude_entries", "llm_reminder"):
        op.drop_column('gratitude_entries', 'llm_reminder')
    # ### end Alembic commands ###
