"""add llm_reasoning_trace

Revision ID: f2120385af2d
Revises: b1f0a48c6b94
Create Date: 2025-05-12 23:09:55.101971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2120385af2d'
down_revision: Union[str, None] = 'b1f0a48c6b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gratitude_entries', sa.Column('llm_reasoning_trace', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gratitude_entries', 'llm_reasoning_trace')
    # ### end Alembic commands ###
